# Proposed new skill generated by Praxis on 2025-06-09T21:45:04.597280
# Task: Develop a skill that can translate text between multiple languages, supporting at least English, Spanish, and French. The skill should be able to handle both single words and full sentences, and should provide accurate translations.

# skills/translator_skill.py
# (Generated by Praxis Autonomous Learning Agent)

import logging

logging.basicConfig(level=logging.INFO)

try:
    from googletrans import Translator  # Consider alternatives if Googletrans is unavailable.
except ImportError:
    logging.error("The 'googletrans' library is required for this skill. Please install it using 'pip install googletrans==4.0.0-rc1'.")
    
def newly_learned_skill(context: Any, text_to_translate: str, target_language: str = "es"):
    """
    Translates text between multiple languages using Google Translate.

    Args:
        context: The context object provided by Praxis.  Has a speak() method.
        text_to_translate: The text to be translated.
        target_language: The target language code (default is "es" for Spanish).  
                         Supports language codes like "en" (English), "fr" (French), "es" (Spanish), etc.  
                         Check Google Translate's supported languages for a complete list.

    Returns:
        None. Prints the translation to the user via context.speak().
    """
    try:
        translator = Translator()
        translated_text = translator.translate(text_to_translate, dest=target_language).text
        context.speak(f"Translation to {target_language}: {translated_text}")
        logging.info(f"Translation successful: '{text_to_translate}' translated to '{translated_text}'")

    except Exception as e:
        context.speak(f"An error occurred during translation: {e}")
        logging.error(f"Translation failed: {e}")


def _test_skill(context: Any):
    """Tests the translation skill."""
    logging.info("Starting translation skill test...")
    newly_learned_skill(context, "Hello, world!", "es")  #Test Spanish
    newly_learned_skill(context, "Bonjour le monde", "en") #Test English
    newly_learned_skill(context, "Hola mundo", "fr") #Test French
    newly_learned_skill(context, "This is a longer sentence to test translation accuracy.", "fr")
    logging.info("Translation skill test completed.")